### ISSUE TITLE
Downloading data

### ISSUE THREAD

**Issue by mortezaezzabady** [XinhaoMei/ACT#1]
Hi,
can you provide another way for us to download audiocaps data? I can't use Baidu.

**Comment by mhondaitc** [comment]
Dr. Mei,
I have the same request.
I am very glad if you set up other channel for sharing your AudioCaps dataset.

**Comment by XinhaoMei** [comment]
Hi, thanks for your attention.
Do you have any recommended channels for uploading?

**Comment by XinhaoMei** [comment]
> Hi, can you provide another way for us to download audiocaps data? I can't use Baidu.



> Dr. Mei, I have the same request. I am very glad if you set up other channel for sharing your AudioCaps dataset.

Hi, thanks for your attention.
Do you have any recommended channels for uploading?

**Comment by mhondaitc** [comment]
Dr. Mei,

Can you use google drive?

Best regards,
Makoto Honda

2022年1月18日火曜日 XinhaoMei ***@***.***>:

**Comment by XinhaoMei** [comment]
Dear all,
Please find the [google drive link](https://drive.google.com/drive/folders/1e5v-u7qRtmKAzQVMbBSy7CU-tp1nA0su?usp=sharing)
Thanks!

**Comment by mhondaitc** [comment]
Dr. Mei,

Thanks for your quick sharing the audiocaps data.
Now I am enjoying your ACT codes working well.

Best regards,
Makoto Honda


2022年1月18日(火) 20:15 XinhaoMei ***@***.***>:
