### ISSUE TITLE
Can you upload ACT_m_scratch and ACT_m_DeiT as well?

### ISSUE THREAD

**Issue by stet-stet** [XinhaoMei/ACT#3]
Hello, Dr. Mei! Thank you for open-sourcing this awesome work. 

While the procedure to reproduce ACT_m_DeiT and ACT_m_scratch was sufficiently explained, I was wondering if it would be possible to upload them / otherwise obtain from you the model you used to produce the Results Table - Just like you did with the ACT_*_AudioSet_DeiT series.

Thank you!

**Comment by XinhaoMei** [comment]
Hi, thanks for yout interests.
Unfortunately, I didn't keep these checkpoints. Maybe you can train them by changing some settings.
So sorry for this.
