### ISSUE TITLE
evaluation problem

### ISSUE THREAD

**Issue by paozhuanis1** [XinhaoMei/ACT#6]
Hello, nice work!
After I replicate your work, and I got the model trained from scratch by myself ( the encoder used pretrained_model -- audioset_deit).
And when I want to evaluate the model, I set the config.path.eval_model to the path where my model is,  but when I load the state_dict, there is something wrong.

![{7C940F16-DC11-4467-8277-9B5C006A1AC4}](https://github.com/XinhaoMei/ACT/assets/86753693/f88757bd-935e-47af-98b0-d184afdd8857)

I do not know why there is nothing about decoder? Could you help me with this problem? Thank you for your early reply!!!

**Comment by XinhaoMei** [comment]
> Hello, nice work! After I replicate your work, and I got the model trained from scratch by myself ( the encoder used pretrained_model -- audioset_deit). And when I want to evaluate the model, I set the config.path.eval_model to the path where my model is, but when I load the state_dict, there is something wrong.
> 
> ![{7C940F16-DC11-4467-8277-9B5C006A1AC4}](https://private-user-images.githubusercontent.com/86753693/291177474-f88757bd-935e-47af-98b0-d184afdd8857.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTk5MjMsIm5iZiI6MTcwMjk5OTYyMywicGF0aCI6Ii84Njc1MzY5My8yOTExNzc0NzQtZjg4NzU3YmQtOTM1ZS00N2FmLTk4YjAtZDE4NGFmZGQ4ODU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODk1MmVmZGZhNGJhYmYyOTEwYTk3Y2FmMzZjMmY5OGI3ZTU4NmIxOWE3NWIwNTk4YjRlMDk2OGJjZTI4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I6iO_KdpEmd7S3nwg6bI1qfrfLxJTFzwv1xQDEjS_h4)
> 
> I do not know why there is nothing about decoder? Could you help me with this problem? Thank you for your early reply!!!

Hello,

Could you please check whether the hyperparameters of the evaluation model (e.g., number of layers) match those of your pretrained checkpoint?
