### ISSUE TITLE
train using clotho dataset

### ISSUE THREAD

**Issue by paozhuanis1** [XinhaoMei/ACT#8]
Hello, nice work!!!

I want to know if you have the code for training on clotho dataset.
Thank you for you early response!!!

**Comment by XinhaoMei** [comment]
Hello,

If you want to train it on Clotho, you could adapt the dataloader for Clotho. But the ACT model only accepts 10-second audio clip, therefore, you might need to crop the audio clips to 10-second, which will lead to information loss.
