### ISSUE TITLE
concrete information about w2v_512.model

### ISSUE THREAD

**Issue by paozhuanis1** [XinhaoMei/ACT#9]
Hello, sorry for bothering you.
I want to konw the concrete information about w2v_512.model which you offered in the pretrained_model.
The infos like the origin downloading link , the corpus to train and so on.
Because I want to train on my own dataset, but when I ran, there was a problem about ''Key 'xxx' not present''

**Comment by XinhaoMei** [comment]
Hi,

The word2vec model was trained on the corpus of training set from AudioCaps.  When you train on your dataset, some words might not exist in the vocabulary of AudioCaps. You could train your own word2vec model or even use randomly initialized embeddings.

**Comment by paozhuanis1** [comment]
I am wandering 
1.whether you remove the word in stopwords
2.whether you get the stem of the words,
3. whther you set the min_count = 1 or others

**Comment by XinhaoMei** [comment]
> Thanks! But I have another question. I am wandering 1.whether you remove the word in stopwords 2.whether you get the stem of the words, 3. whther you set the min_count = 1 or others Sorry for bothering you again! Thank you for your early response!!!

Please find the example script here. https://github.com/XinhaoMei/DCASE2021_task6_v2/blob/main/word2vec_train.py
